import type { BuyerProfile, Drop, Source } from "./types";

export const defaultBuyer: BuyerProfile = {
  name: "Mohit",
  phone: "+1 *** *** 1282",
  address: "Ellis Town Dr, Tracy, CA",
  neighborhood: "Tracy",
  radius: 8,
  diets: ["veg", "jain"],
  cuisines: ["Gujarati", "South Indian"],
  pickupTarget: "Tonight 6-8 PM"
};

export const sources: Source[] = [
  {
    id: "src-asha-wa",
    name: "Asha's Menu Group",
    type: "WhatsApp group",
    area: "Tracy",
    scanCadence: "9 AM, 12 PM, 3 PM, 5 PM, 7 PM",
    format: "admin menu text + occasional images",
    noise: "low",
    status: "connected"
  },
  {
    id: "src-dosa-flyer",
    name: "Mountain House Food Flyers",
    type: "Forwarded menu",
    area: "Mountain House",
    scanCadence: "on forward + 4 PM digest prep",
    format: "image OCR",
    noise: "medium",
    status: "ready"
  },
  {
    id: "src-patel-public",
    name: "Patel Tiffins Weekly Listing",
    type: "Public listing",
    area: "Lathrop",
    scanCadence: "daily morning",
    format: "weekly menu page",
    noise: "low",
    status: "connected"
  },
  {
    id: "src-green-wa",
    name: "Green Bowl Seller Group",
    type: "WhatsApp group",
    area: "Mountain House",
    scanCadence: "11 AM, 4 PM, 6 PM",
    format: "seller-owned group",
    noise: "low",
    status: "connected"
  },
  {
    id: "src-sulekha",
    name: "Sulekha-style Local Listings",
    type: "Public listing",
    area: "Tracy/Lathrop",
    scanCadence: "daily",
    format: "business profile scrape",
    noise: "medium",
    status: "ready"
  }
];

export const drops: Drop[] = [
  {
    id: "drop-asha-thali",
    seller: "Asha's Gujarati Kitchen",
    sellerType: "home tiffin",
    area: "Tracy",
    pickupAddress: "Corral Hollow Rd & Grant Line Rd, Tracy, CA",
    distanceMiles: 2.4,
    menu: "Gujarati thali: rotli, dal, rice, aloo shaak, kachumber",
    price: 14,
    pickupWindow: "Tonight 6-7:30 PM",
    availability: "12 plates left",
    sourceId: "src-asha-wa",
    labels: ["veg", "jain", "no onion/garlic", "tiffin"],
    cuisine: ["Gujarati"],
    confidence: "verified",
    sourceSnippet: "Admin post: Jain thali available today. No onion/garlic. Pickup 6-7:30. 12 plates.",
    cadence: "daily",
    updatedAt: "3:42 PM"
  },
  {
    id: "drop-ritu-snacks",
    seller: "Jain Snacks by Ritu",
    sellerType: "snacks specialist",
    area: "Tracy",
    pickupAddress: "Eleventh St & Bessie Ave, Tracy, CA",
    distanceMiles: 4.2,
    menu: "Jain dhokla, khandvi, thepla packs",
    price: 12,
    pickupWindow: "Today 4-6 PM",
    availability: "9 packs left",
    sourceId: "src-dosa-flyer",
    labels: ["veg", "jain", "eggless", "snacks"],
    cuisine: ["Gujarati"],
    confidence: "verified",
    sourceSnippet: "Forwarded flyer says Jain snacks today, pickup 4-6 PM, limited packs.",
    cadence: "same-day",
    updatedAt: "2:58 PM"
  },
  {
    id: "drop-sri-dosa",
    seller: "Sri Dosa Home Foods",
    sellerType: "South Indian home cook",
    area: "Mountain House",
    pickupAddress: "Central Pkwy & Main St, Mountain House, CA",
    distanceMiles: 7.1,
    menu: "Idli, dosa batter, sambar, coconut chutney",
    price: 11,
    pickupWindow: "Tonight 5:30-8 PM",
    availability: "few left",
    sourceId: "src-dosa-flyer",
    labels: ["veg", "vegan-friendly"],
    cuisine: ["South Indian"],
    confidence: "likely",
    sourceSnippet: "Flyer image has no dairy visible, but vegan not explicitly stated.",
    cadence: "same-day",
    updatedAt: "4:05 PM"
  },
  {
    id: "drop-green-bowl",
    seller: "Green Bowl Tiffin",
    sellerType: "vegan tiffin",
    area: "Mountain House",
    pickupAddress: "Mountain House Pkwy, Mountain House, CA",
    distanceMiles: 8.4,
    menu: "Vegan khichdi bowl, roasted vegetables, cilantro chutney",
    price: 13,
    pickupWindow: "Tonight 6:30-7:30 PM",
    availability: "7 bowls left",
    sourceId: "src-green-wa",
    labels: ["vegan", "veg", "nut-free", "tiffin"],
    cuisine: ["Gujarati", "Indian fusion"],
    confidence: "verified",
    sourceSnippet: "Seller post: vegan khichdi bowl, nut-free, 7 bowls left.",
    cadence: "daily",
    updatedAt: "3:51 PM"
  },
  {
    id: "drop-punjab-rasoi",
    seller: "Punjab Rasoi",
    sellerType: "home dinner plates",
    area: "Tracy",
    pickupAddress: "MacArthur Dr & Lowell Ave, Tracy, CA",
    distanceMiles: 5.8,
    menu: "Paneer tikka masala, dal makhani, jeera rice, naan",
    price: 16,
    pickupWindow: "Tonight 6-8 PM",
    availability: "18 plates left",
    sourceId: "src-asha-wa",
    labels: ["veg"],
    cuisine: ["Punjabi"],
    confidence: "verified",
    sourceSnippet: "Menu text confirms vegetarian paneer/dal dinner plates.",
    cadence: "same-day",
    updatedAt: "4:20 PM"
  },
  {
    id: "drop-patel-weekly",
    seller: "Patel Tiffins",
    sellerType: "weekly meal plan",
    area: "Lathrop",
    pickupAddress: "River Islands Pkwy, Lathrop, CA",
    distanceMiles: 11.8,
    menu: "Weekly tiffin plan: 5 dinners, rotating Gujarati/Punjabi menu",
    price: 65,
    pickupWindow: "Starts Monday",
    availability: "accepting weekly orders",
    sourceId: "src-patel-public",
    labels: ["veg", "tiffin", "weekly"],
    cuisine: ["Gujarati", "Punjabi"],
    confidence: "verified",
    sourceSnippet: "Public weekly listing with vegetarian menu and Monday start.",
    cadence: "weekly",
    updatedAt: "9:30 AM"
  },
  {
    id: "drop-biryani",
    seller: "Biryani Uncle",
    sellerType: "specialty pop-up",
    area: "Lathrop",
    pickupAddress: "Louise Ave, Lathrop, CA",
    distanceMiles: 12.3,
    menu: "Chicken dum biryani family tray",
    price: 38,
    pickupWindow: "Friday preorder",
    availability: "preorder",
    sourceId: "src-sulekha",
    labels: ["non-veg", "catering", "preorder"],
    cuisine: ["Hyderabadi"],
    confidence: "verified",
    sourceSnippet: "Public listing: Friday chicken dum biryani family trays.",
    cadence: "advance",
    updatedAt: "10:15 AM"
  }
];
